feat(o-shop): add product form, modify form property values
jesus-mdz/apprentice-react-o-shop pull request #7
Opened 2020-08-27 20:22 UTC by jesus-mdz

2020-08-27 20:32 UTC, ahaly92 commented on src/components/Auth/ProductForm.js
> +        inputArray={[
pull this array into a const file in the Auth folder and import it in here

2020-08-27 20:32 UTC, ahaly92 commented on src/components/Auth/RegisterForm.js
> +      inputArray={[
same here

2020-08-27 20:35 UTC, ahaly92 commented on src/components/Auth/ProductForm.js
> +        restart={() => {
can you make this an optional parameter so you don't have to pass in a function that doesnt do anything

2020-08-27 20:35 UTC, ahaly92 requested changes
Nice work! A lot of really great stuff here. Left a few comments

2020-08-28 01:46 UTC, ahaly92 approved these changes

2020-08-28 14:16 UTC, mmevans approved these changes

2020-08-28 14:47 UTC, merged